#!/usr/bin/env python3

import argparse
import yaml
import jinja2
import logging
import os
import re

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def setup_argparse():
    """
    Sets up the argument parser for the script.

    Returns:
        argparse.ArgumentParser: The argument parser object.
    """
    parser = argparse.ArgumentParser(description="Generates a rollback script from a hardening script with 'before' state logging.")
    parser.add_argument("hardening_script", help="Path to the hardening script.")
    parser.add_argument("rollback_script", help="Path to the output rollback script.")
    parser.add_argument("--dry-run", action="store_true", help="Perform a dry run without writing the rollback script.")
    return parser

def extract_rollback_commands(hardening_script_path):
    """
    Extracts rollback commands from the hardening script.
    Assumes the hardening script logs the 'before' state.

    Args:
        hardening_script_path (str): Path to the hardening script.

    Returns:
        list: A list of rollback commands extracted from the hardening script.
              Returns an empty list if no rollback commands are found or an error occurs.
    """
    rollback_commands = []
    try:
        with open(hardening_script_path, 'r') as f:
            for line in f:
                # Look for lines that log the 'before' state
                match = re.search(r"^#BEFORE: (.*)$", line) # Example of how to identify 'before' state logging.  Adjust regex as needed.
                if match:
                    command = match.group(1).strip()
                    rollback_commands.append(command)
        if not rollback_commands:
            logging.warning(f"No rollback commands found in {hardening_script_path}. Ensure the hardening script logs the 'before' state of changes.")

    except FileNotFoundError:
        logging.error(f"Hardening script not found: {hardening_script_path}")
    except Exception as e:
        logging.error(f"Error reading hardening script: {e}")
    return rollback_commands

def generate_rollback_script(rollback_commands, rollback_script_path, dry_run=False):
    """
    Generates the rollback script from the extracted commands.

    Args:
        rollback_commands (list): List of rollback commands.
        rollback_script_path (str): Path to the output rollback script.
        dry_run (bool): If True, performs a dry run without writing the script.
    """
    try:
        if not rollback_commands:
            logging.warning("No rollback commands to generate.")
            return

        # Reverse the commands to revert in the correct order (LIFO).
        rollback_commands.reverse()

        script_content = "#!/bin/bash\n\n"
        script_content += "# Rollback script generated by harden-chs-RollbackScriptGenerator\n\n"
        script_content += "# Reverting changes in reverse order\n\n"

        for command in rollback_commands:
            script_content += f"{command}\n"

        if dry_run:
            logging.info("Dry run: Rollback script content:\n" + script_content)
            return

        with open(rollback_script_path, 'w') as f:
            f.write(script_content)

        # Make the script executable
        os.chmod(rollback_script_path, 0o755)  # Security: Ensure script is executable by owner

        logging.info(f"Rollback script generated successfully: {rollback_script_path}")

    except Exception as e:
        logging.error(f"Error generating rollback script: {e}")


def main():
    """
    Main function to drive the rollback script generation process.
    """
    parser = setup_argparse()
    args = parser.parse_args()

    hardening_script_path = args.hardening_script
    rollback_script_path = args.rollback_script
    dry_run = args.dry_run

    # Input validation: Check if the hardening script exists.
    if not os.path.exists(hardening_script_path):
        logging.error(f"Hardening script not found: {hardening_script_path}")
        return

    logging.info(f"Generating rollback script for: {hardening_script_path}")

    rollback_commands = extract_rollback_commands(hardening_script_path)
    if rollback_commands:
      generate_rollback_script(rollback_commands, rollback_script_path, dry_run)
    else:
      logging.warning("No rollback commands extracted. Rollback script will not be generated.")


if __name__ == "__main__":
    main()